Bug fixes, new URL param
concord-consortium/flooding-model pull request #22
Opened 2020-09-17 11:06 UTC by pjanik

1. The previous layout based on flex and large flex-grow values didn't work too well with ChartJS and it was causing issues in Safari. Now things should look fine both in Safari and when you resize the window (e.g. enter and exit full-screen mode).

2. The app will no longer crash when you try to open the cross-section tab too early.

3. There's a new URL param activeTab, e.g. ?activeTab=gauge2 to open the app with gauge 2 cross-section selected (Trudi requested that).

2020-09-21 17:57 UTC, dstrawberrygirl requested changes
I think a small adjust is needed to get the bottom bar to work on Safari (and Chrome, which is essentially Safari) on iPad as noted in the comment. Also, iPad cannot yet add levees, so may need some tweaks there. Does the map need to be rotated in this simulation mode?

2020-09-21 17:57 UTC, dstrawberrygirl commented on src/components/app.scss
> +  bottom: 0;
The bottomBar I think needs a bit of adjustment - iPad rendering both portrait and landscape cuts off the lowest parts of the bar, so you can't read the slider values for amount of rain starting water level, etc.

2020-09-21 18:08 UTC, pjanik commented on src/components/app.scss
> +  bottom: 0;
Is this happening on real iPad or desktop Chrome in the device test mode?
I can see that in the latter (actually for any size and any device), but wondering if it's a glitch just there or also on the real devices.

2020-09-21 19:29 UTC, dstrawberrygirl commented on src/components/app.scss
> +  bottom: 0;
this was visible on the iPad I used to test (iPad Air 2) in both Chrome and Safari, issue has been present for a while I am guessing since it is also visible on the version embedded in the activity player if you load that on the iPad

2020-09-22 16:21 UTC, pjanik commented on src/components/app.scss
> +  bottom: 0;
Thanks, it's been fixed in the last commit. It turns out MUI theme has some media queries like: `@media (pointer: coarse)`. I've locked affected values using !important in our custom GeoHazard theme.

2020-09-22 16:29 UTC, pjanik commented
The build was fine so I'm going to go ahead and merge this PR, as the only comment has been addressed.

2020-09-22 16:29 UTC, merged